services:
  - type: web
    name: projeto-downloader
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg"
    startCommand: "gunicorn app:app -w 4 -b 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
